package com.easyroute.constant;

public enum Event {
    MAIN_ACTIVITY_MY_LOCATION_BUTTON_CLICKED,
    MAIN_ACTIVITY_NAVIGATE_BUTTON_CLICKED,
    MAIN_ACTIVITY_SOURCE_PLACE_SELECTED,
    MAIN_ACTIVITY_DESTINATION_PLACE_SELECTED,
    MAIN_ACTIVITY_SECOND_PLACE_SELECTED,
    MAIN_ACTIVITY_ROUTE_PARAMETERS_CHANGED,
    MAIN_ACTIVITY_SOURCE_MARKER_CLICKED,
    MAIN_ACTIVITY_DESTINATION_MARKER_CLICKED,
    MAIN_FRAGMENT_TIME_CHANGED,
    VEHICLE_INFO_DIALOG_SAVE,
    ROUTE_FRAGMENT_ROUTE_SELECTED,
}
